name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'charts/openhands/**'
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Chart version to release'
        required: false
        default: ''

env:
  REGISTRY: ghcr.io

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.12.1'

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set repository owner
        run: |
          echo REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - name: Package and push chart
        run: |
          cd charts

          # Package the chart
          helm package openhands

          # Get chart version
          CHART_VERSION=$(helm show chart openhands | grep '^version:' | awk '{print $2}')
          echo "Chart version: $CHART_VERSION"

          # Push to GHCR using dynamic repository owner for charts
          helm push openhands-${CHART_VERSION}.tgz oci://ghcr.io/${REPO_OWNER}/openhands-helm

      - name: Lint and test chart
        run: |
          cd charts
          helm lint openhands

      - name: Test chart template
        run: |
          cd charts
          helm template test-release openhands --debug

      - name: Upload chart artifacts
        uses: actions/upload-artifact@v4
        with:
          name: helm-charts
          path: charts/openhands-*.tgz
